backend:
  name: git-gateway
  branch: netlify-cms

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/test/test.md"
        label: "Test"
        name: "test"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "test-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/test"}
          - {label: "Title", name: "title", widget: "string"}
  - name: "shops"
    label: "Shops"
    folder: "src/pages/shops"
    create: true
    slug: "{{slug}}" #filename
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "shop-page"}
      - {label: "Path", name: "path", widget: "string", default: "shops/"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Postcode", name: "postcode", widget: "string"}
      - {label: "List", name: "list", widget: "list"}
  
  - name: "postcodes"
    label: "Postcodes"
    files:
      - file: "src/pages/postcodetest.json"
        label: "PostcodeTest"
        name: "postcodetest"
        extension: "json"
        format: "json"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "shop-page"}